did not delete in original areas
aad-for-linux/docker pull request #1
Opened 2021-10-11 15:27 UTC by Ada-Codina

only copied,
did not delete

2021-10-11 17:21 UTC, oxr463 commented
Assuming this is related to https://github.com/aad-for-linux/aad-for-linux/issues/19

2021-10-11 17:35 UTC, Ada-Codina commented
yes

2021-10-11 19:17 UTC, oxr463 requested changes

2021-10-11 19:17 UTC, oxr463 commented on libnss-aad/docker/amazon/2018.03/Dockerfile
> +FROM amazonlinux:2018.03
We're dropping support for Amazon Linux 2, so we can delete this file.

2021-10-11 19:17 UTC, oxr463 commented on libnss-aad/docker/amazon/Dockerfile
> +FROM amazonlinux:2
We can also delete this one.

2021-10-11 19:17 UTC, oxr463 commented on libnss-aad/docker/debian/Dockerfile
> +FROM debian:9.7
Let's remove the `docker` subdirectory, e.g., `libnss_aad/debian/Dockerfile`

Also, let's bump this to Debian 11.0:

```suggestion
FROM debian:11.0
```

2021-10-11 19:17 UTC, oxr463 commented on libnss-aad/docker/debian/Dockerfile
> +RUN echo "deb http://http.us.debian.org/debian sid main" \
We'll need to replace `sid` with `bullseye`.

2021-10-11 19:17 UTC, oxr463 commented on libnss-aad/docker/ubuntu/Dockerfile
> +FROM ubuntu:18.04
Let's also rename and bump, e.g., `libnss_aad/ubuntu/Dockerfile`

```suggestion
FROM ubuntu:20.04
```

2021-10-11 19:17 UTC, oxr463 commented on libnss-aad/docker/ubuntu/Dockerfile
> +RUN echo "deb http://http.us.debian.org/debian sid main" \
Replace sid with bullseye

2021-10-11 19:17 UTC, oxr463 commented on openvpn-auth-aad/docker/debian/Dockerfile
> +FROM aad-for-linux/pam_aad:debian
Let's rename this too, e.g., `openvpn_auth_aad/debian/Dockerfile`

2021-10-11 19:17 UTC, oxr463 commented on openvpn-auth-aad/docker/ubuntu/Dockerfile
> +FROM aad-for-linux/pam_aad:ubuntu
Rename, e.g., `openvpn_auth_aad/ubuntu/Dockerfile`

2021-10-11 19:17 UTC, oxr463 commented on pam_aad/docker/amazon/2018.03/Dockerfile
> +FROM amazonlinux:2018.03
Delete this file

2021-10-11 19:17 UTC, oxr463 commented on pam_aad/docker/amazon/Dockerfile
> +FROM amazonlinux:2
Delete this one too

2021-10-11 19:17 UTC, oxr463 commented on pam_aad/docker/debian/Dockerfile
> +FROM debian:9.7
Rename, e.g., `pam_aad/debian/Dockerfile`

2021-10-11 19:17 UTC, oxr463 commented on pam_aad/docker/debian/Dockerfile
> +RUN echo "deb http://http.us.debian.org/debian sid main" \
Replace sid with bullseye

2021-10-11 19:17 UTC, oxr463 commented on pam_aad/docker/ubuntu/Dockerfile
> +FROM ubuntu:18.04
Rename and bump, e.g., `pam_aad/ubuntu/Dockerfile`

```suggestion
FROM ubuntu:20.04
```

2021-10-11 19:22 UTC, oxr463 commented on libnss-aad/docker/amazon/Dockerfile
> -FROM amazonlinux:2
No, not just the line. The whole file. You could actually just go ahead and delete the whole directory, i.e., `rm -rf libnss-aad/docker/amazon`

2021-10-11 19:58 UTC, outzhu reviewed
that should do it.

2021-10-11 20:43 UTC, oxr463 commented on openvpn-auth-aad/debian/Dockerfile
> +FROM openvpn_auth_aad/debian/Dockerfile
That's the file path, not the docker image tag. We can leave the old name how it was.

2021-10-11 20:45 UTC, oxr463 commented on pam_aad/debian/Dockerfile
> +FROM pam_aad/debian/Dockerfile
Let's put the old line back and just change the version to `11.0`. Then we need to rename the file itself to `pam_aad/debian/Dockerfile`.

2021-10-12 14:11 UTC, outzhu commented
Made changes. Please review.

2021-10-13 15:38 UTC, oxr463 commented on pam_aad/rocky/Dockerfile
> +FROM rocky:8.4
```suggestion
FROM rockylinux/rockylinux:8.4
```

2021-10-13 15:38 UTC, oxr463 commented on libnss-aad/alpine/Dockerfile
> +    apt update && apt install -y \
For alpine, we need to use `apk`, not `apt`. All the package names are slightly different too.

Reference(s):
- https://pkgs.alpinelinux.org/packages

2021-10-27 16:13 UTC, oxr463 commented
@Ada-Codina what's the status on this?

2021-10-27 16:24 UTC, outzhu commented
Checked for the packages specific versions that were available in rocky/alpine, rename the ones that were there and removed the ones that weren't.

I left the lines empty so you can check what's been rename/removed.

2021-10-27 16:38 UTC, oxr463 commented
> Checked for the packages specific versions that were available in rocky/alpine, rename the ones that were there and removed the ones that weren't.
> 
> I left the lines empty so you can check what's been rename/removed.

Can you remove the empty lines and make a list of missing packages as a comment?

2021-10-27 16:50 UTC, oxr463 requested changes
A few more things:

- [x] Please rename the `libnss-aad` directory to `libnss_aad`.
- [ ] Once all the changes have been made, we need to test by building each docker image (Let me know if you need help).

2021-10-27 16:50 UTC, oxr463 commented on libnss-aad/alpine/Dockerfile
> +ARG DEBVER
DEBVER stands for Debian Version. We don't need this anymore since this is Alpine.

2021-10-27 16:50 UTC, oxr463 commented on libnss-aad/alpine/Dockerfile
> +RUN echo "deb http://http.us.debian.org/debian bullseye main" \
Why are we adding a Debian repository to Alpine? Let's take this line out.

2021-10-27 16:50 UTC, oxr463 commented on libnss-aad/alpine/Dockerfile
> +    dpkg -i "libsds-dev_${SDSDEBVERSION}_amd64.deb"
This is all for the Debian package. We can remove it.

For Alpine, I've already ported the package here, https://pkgs.alpinelinux.org/packages?name=libsds&branch=edge

We just need to add it to the packages list above.

2021-10-27 16:50 UTC, oxr463 commented on libnss-aad/alpine/Dockerfile
> +    dpkg -i "../libnss-aad_${VERSION}-${DEBVER}_amd64.deb"
We need to use `make`, not `debuild`. This is all for the Debian package.

2021-10-27 16:50 UTC, oxr463 commented on libnss-aad/rocky/Dockerfile
> +    dpkg -i "libsds-dev_${SDSDEBVERSION}_amd64.deb"
We're going to need to package SDS for Rocky Linux. This is for Debian.

2021-10-27 16:50 UTC, oxr463 commented on libnss-aad/rocky/Dockerfile
> +    dpkg -i "../libnss-aad_${VERSION}-${DEBVER}_amd64.deb"
This is for Debian. Rocky is similar to Amazon Linux. Check how I did it there, https://github.com/aad-for-linux/pam_aad/blob/master/docker/amazon/Dockerfile#L36

2021-10-27 16:50 UTC, oxr463 commented on openvpn-auth-aad/alpine/Dockerfile
> +ARG DEBVER
Please remove this.

2021-10-27 16:50 UTC, oxr463 commented on openvpn-auth-aad/alpine/Dockerfile
> +    dpkg -i "../openvpn-auth-aad_${VERSION}-${DEBVER}_amd64.deb"
We can't use `debuild` on Alpine. Please rewrite using `make` instead.

2021-10-27 16:50 UTC, oxr463 commented on openvpn-auth-aad/rocky/Dockerfile
> +ARG DEBVER
Please remove.

2021-10-27 16:50 UTC, oxr463 commented on openvpn-auth-aad/rocky/Dockerfile
> +    dpkg -i "../openvpn-auth-aad_${VERSION}-${DEBVER}_amd64.deb"
Please rewrite with `make`.

2021-10-27 16:50 UTC, oxr463 commented on pam_aad/alpine/Dockerfile
> +ARG DEBVER
Please remove.

2021-10-27 16:50 UTC, oxr463 commented on pam_aad/alpine/Dockerfile
> +RUN echo "deb http://http.us.debian.org/debian bullseye main" \
Please remove.

2021-10-27 16:50 UTC, oxr463 commented on pam_aad/alpine/Dockerfile
> +    dpkg -i "libsds-dev_${SDSDEBVERSION}_amd64.deb"
Use libsds package from Alpine instead.

2021-10-27 16:50 UTC, oxr463 commented on pam_aad/alpine/Dockerfile
> +    dpkg -i "../libpam-aad_${VERSION}-${DEBVER}_amd64.deb"
Please use `make` instead of `debuild`.

2021-10-27 16:50 UTC, oxr463 commented on pam_aad/rocky/Dockerfile
> +ARG DEBVER
Please remove.

2021-10-27 16:50 UTC, oxr463 commented on pam_aad/rocky/Dockerfile
> +RUN echo "deb http://http.us.debian.org/debian bullseye main" \
Please remove.

2021-10-27 16:50 UTC, oxr463 commented on pam_aad/rocky/Dockerfile
> +    dpkg -i "libsds-dev_${SDSDEBVERSION}_amd64.deb"
We need to port SDS since we can't use the Debian package.

2021-10-27 16:50 UTC, oxr463 commented on pam_aad/rocky/Dockerfile
> +    dpkg -i "../libpam-aad_${VERSION}-${DEBVER}_amd64.deb"
We need to use `make`.

2021-10-27 17:44 UTC, outzhu commented
### libnss_aad's missing packeges

**Alpine's Dockerfile**
autopoint
build-essential
debhelper
devscripts
libcurl4-openssl-dev
libjwt-dev
libssl-dev
libxcrypt-dev
pkg-config

**Rocky's Dockerfile**
autopoint
build-essential
debhelper
devscripts
libjwt-dev
libsodium-dev
libssl-dev
pkg-config

### pam_aad's missing packages

**Alpine's Dockerfile**
build-essential
debhelper
devscripts
libcurl4-openssl-dev
libjwt-dev
libssl-dev
libtool
pkg-config
uuid-dev

**Rocky's Dockerfile**
build-essential
debhelper
devscripts
libcurl4-openssl-dev
libjwt-dev
libpam0g-dev
libssl-dev
pkg-config
uuid-dev

2021-10-27 18:06 UTC, outzhu commented on libnss-aad/rocky/Dockerfile
> +    dpkg -i "libsds-dev_${SDSDEBVERSION}_amd64.deb"
https://github.com/antirez/sds package this for Rocky Linux?

2021-10-27 18:10 UTC, oxr463 commented on libnss-aad/rocky/Dockerfile
> +    dpkg -i "libsds-dev_${SDSDEBVERSION}_amd64.deb"
Yes, (See: https://github.com/aad-for-linux/rpm/issues/2).

2021-10-27 18:32 UTC, outzhu commented on libnss-aad/rocky/Dockerfile
> +    dpkg -i "../libnss-aad_${VERSION}-${DEBVER}_amd64.deb"
```
RUN make depends && \
    LIB_DIR=/lib64 make -e install
```
for libnss_aad
https://github.com/aad-for-linux/libnss-aad/blob/master/docker/amazon/Dockerfile

and for pam_aad
``` 
RUN ./bootstrap.sh && \
    ./configure --with-pam-dir="${PAMROC}" && \
    make && make install
```
left openvpn-auth-aad alone for now

2021-11-02 20:25 UTC, closed without merging

2021-11-02 20:32 UTC, oxr463 commented
>  [ ] Once all the changes have been made, we need to test by building each docker image (Let me know if you need help).

See: https://github.com/aad-for-linux/docker/issues/2

2021-11-03 03:24 UTC, oxr463 commented on libnss-aad/rocky/Dockerfile
> +    dpkg -i "libsds-dev_${SDSDEBVERSION}_amd64.deb"
Actually, we're going to rip it out.